server:
  port: 8000

spring:
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          "[/**]":
            allowed-origins:
              - "https://nyangmong.com"
            allowed-methods:
              - GET
              - POST
              - DELETE
              - PATCH
              - PUT
              - OPTIONS
            allowed-headers:
              - Content-Type
              - Authorization
              - X-Requested-With
            allow-credentials: true

      routes:
        - id: user-service
          uri: http://user-service.default.svc.cluster.local:8086
          predicates:
            - Path=/user-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /${segment}
            - AuthorizationHeaderFilter

        - id: scheduler-service
          uri: lb://SCHEDULER-SERVICE
          predicates:
            - Path=/scheduler-service/**
          filters:
            - RewritePath=/scheduler-service/(?<segment>.*), /${segment}
            - AuthorizationHeaderFilter

        - id: main-service
          uri: http://main-service.default.svc.cluster.local:8004
          predicates:
            - Path=/main-service/**, /v3/api-docs/**, /swagger-ui.html, /swagger-ui/**, /swagger-resources/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/main-service/(?<segment>.*), /${segment}
            - AuthorizationHeaderFilter

        - id: festival-service
          uri: http://festival-service.default.svc.cluster.local:8083
          predicates:
            - Path=/festival-service/**, /v3/api-docs/**, /swagger-ui.html, /swagger-ui/**, /swagger-resources/**
          filters:
            - RewritePath=/festival-service/(?<segment>.*), /${segment}
            - AuthorizationHeaderFilter

        - id: animalboard-service
          uri: http://animalboard-service.default.svc.cluster.local:8081
          predicates:
            - Path=/animalboard-service/**, /v3/api-docs/**, /swagger-ui.html, /swagger-ui/**, /swagger-resources/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/animalboard-service/(?<segment>.*), /${segment}
            - AuthorizationHeaderFilter

        - id: board-service
          uri: http://board-service.default.svc.cluster.local:8082
          predicates:
            - Path=/board-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/board-service/(?<segment>.*), /${segment}
            - AuthorizationHeaderFilter

        - id: admin-service
          uri: http://admin-service.default.svc.cluster.local:8080
          predicates:
            - Path=/admin-service/**, /v3/api-docs/**, /swagger-ui.html, /swagger-ui/**, /swagger-resources/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/admin-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter

        - id: map-service
          uri: http://map-service.default.svc.cluster.local:8085
          predicates:
            - Path=/map-service/**, /v3/api-docs/**, /swagger-ui.html, /swagger-ui/**, /swagger-resources/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/map-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter