server:
  port: 0

spring:
  application:
    name: user-service

oauth2:
  kakao:
    client-id: # push ?? ? ????? ????!
    redirect-uri: # ?? ??? ??? ? -> ??? ???? ?? ?? ???? ??? ??

imagePath:
  url: C:\nyangmong_image\user_profile