server:
  port: 0

spring:
  application:
    name: board-service

imagePath:
  thumbnail:
    url: C:\nyangmorg_image\board_thumbnaiImage
#    url: /Users/ubing/Desktop/nyangmong/images/board_thumbnaiImage/

